/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adamcarter' at '5/12/16 7:48 PM' with Gradle 2.9
 *
 * @author adamcarter, @date 5/12/16 7:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
