/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adamcarter' at '4/12/16 10:30 PM' with Gradle 2.9
 *
 * @author adamcarter, @date 4/12/16 10:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
